spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 4317
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false